name: PlanetScale Prisma
description: Automatically create database branches and deploy request in Github pull requests
inputs:
  github-token:
    description: "Github token"
    required: true
  planetscale-service-token:
    description: PlanetScale service token
    required: true
  planetscale-service-token-id:
    description: PlanetScale service token id
    required: true
  planetscale-org:
    description: PlanetScale organization
    required: true
  db-name:
    description: Database name
    required: true
  planetscale-main-branch-name:
    description: Main branch name
    required: false
    default: main
  planetscale-branch-prefix:
    description: Branch prefix for database branches
    required: false
    default: pull-request-
  prisma-db-push-command:
    description: Prisma db push command
    required: false
    default: npx prisma db push
outputs:
  database-branch-name:
    description: "The name of the database branch created"
  deploy-request-number:
    description: "The id of the deploy request created"
  deploy-request-state:
    description: "The state of the deploy request created. open or closed"
  deploy-request-approved:
    description: "The approval status of the deploy request created. true or false"
  temporary-database-url:
    description: "DATABASE_URL value for connecting to the branch. This is going to be invalid after action is run"
  temporary-password-name:
    description: "The name of the temporary password created"

runs:
  using: "docker"
  image: "Dockerfile"
  env:
    GITHUB_TOKEN: ${{ inputs.github-token }}
    PLANETSCALE_SERVICE_TOKEN: ${{ inputs.planetscale-service-token }}
    PLANETSCALE_SERVICE_TOKEN_ID: ${{ inputs.planetscale-service-token-id }}
    PLANETSCALE_ORG: ${{ inputs.planetscale-org }}
    DB_NAME: ${{ inputs.db-name }}
    PLANETSCALE_MAIN_BRANCH_NAME: ${{ inputs.planetscale-main-branch-name }}
    PLANETSCALE_BRANCH_PREFIX: ${{ inputs.planetscale-branch-prefix }}
