name: Install
description: Install PlanetScale CLI
runs:
  using: "composite"
  steps:
    - id: install-planetscale-cli
      name: Install PlanetScale CLI
      shell: bash
      env:
        BASE: "https://github.com/planetscale/cli/releases/download"
        VERSION: "0.115.0"
      run: |
        wget "$BASE/v$(echo $VERSION)/pscale_$(echo $VERSION)_linux_$(dpkg --print-architecture).deb" -O /tmp/pscale.deb && \
        sudo dpkg -i /tmp/pscale.deb && \
        rm /tmp/pscale.deb
