

name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  TypeScript:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: node-setup@v2
        with:
          node-version: "16"
      - run: yarn install
      - run: yarn tsc

